<?php 

/**
 * @file
 * Adds a Meetup event feed processor to the Feeds module.
 */
 
/**
 * Implements ctools_plugin_api().
 */

function feeds_meetup_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_meetup_feeds_plugins() {
  $info = array();
  $info['FeedsMeetupEventParser'] = array(
    'name' => 'Meetup.com event parser',
    'description' => 'Parse Meetup event feeds.',
    'help' => 'Use PHP SimpleXML parser to parse Meetup event feeds.',
    'handler' => array(
      'parent' => 'FeedsXPathParserXML',
      'class' => 'FeedsMeetupEventParser',
      'file' => 'FeedsMeetupEventParser.inc',
      'path' => drupal_get_path('module', 'feeds_meetup'),
    ),
  );
  $info['FeedsMeetupEventProcessor'] = array(
    'name' => 'Meetup.com event processor',
    'description' => 'Process Meetup event feeds.',
    'help' => 'Create and update nodes from parsed Meetup event feeds.',
    'handler' => array(
      'parent' => 'FeedsNodeProcessor',
      'class' => 'FeedsMeetupEventProcessor',
      'file' => 'FeedsMeetupEventProcessor.inc',
      'path' => drupal_get_path('module', 'feeds_meetup'),
    ),
  );
  return $info;
}
